version: "3.2"
services:
  jupyter:
    container_name: python-dev
    image: jupyter/scipy-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./projetos/:/home/jovyan
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command: "start-notebook.sh --NotebookApp.token='c239995c45948014e0a721e7d5b2b03c25f1b1d8a8f05764' --NotebookApp.password=''jupyter"
